//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data {
    
    
    public enum AudioIds {
        
        BGM_Mainmenu = 0,
        
        BGM_Tavern = 1,
        
        Card_Fadeout = 2,
        
        CardEffect_Fadeout = 3,
        
        Effect_Card_Selected = 4,
        
        Effect_Card_Drag = 5,
        
        Effect_Card_Drag_Use = 6,
        
        Effect_Card_Drag_Transmute = 7,
        
        Effect_Card_Use_Normal = 8,
        
        Effect_Card_Use_Rare = 9,
        
        Effect_Card_Use_Special = 10,
        
        Effect_Card_Transmute = 11,
        
        Effect_Card_Draw = 12,
        
        Effect_Error = 13,
        
        Effect_Enemy_Attack = 14,
        
        Effect_Enemy_Damaged_S = 15,
        
        Effect_Enemy_Damaged_L = 16,
        
        Effect_Enemy_Damaged_Buff = 17,
        
        Effect_Enemy_Health_Change = 18,
        
        Effect_Enemy_Attack_Change = 19,
        
        Effect_Enemy_Reward_Change = 20,
        
        Effect_Enemy_Die = 21,
        
        Effect_Player_Damaged = 22,
        
        Effect_Player_Heal = 23,
        
        Effect_Player_Draw = 24,
        
        Effect_Battle_Win = 25,
        
        Effect_Battle_Lose = 26,
        
        Effect_Reward_Selected = 27,
        
        Effect_Reward_Skip = 28,
        
        Effect_Shop_Buy = 29,
        
        Effect_Shop_Refresh = 30,
        
        Effect_Shop_Upgrade = 31,
        
        Effect_Shop_Delete = 32,
        
        UI_Mainmenu_Roll = 33,
        
        UI_Button_Touch = 34,
        
        UI_Button_Click = 35,
        
        UI_Mouse_Click = 36,
        
        UI_AVG_Swich = 37,
        
        UI_ChooseCharacterView_Page = 38,
        
        UI_ChooseCharacterView_Pencil = 39,
        
        UI_ChooseLevelView_Page = 40,
        
        UI_ChooseLevelView_Pencil = 41,
    }
    
    #region 
static
    public class AudioIdsExtensions {
        
		public static AudioTable.Entry Data(this AudioIds id) => global::WanFramework.Data.DataSystem.Instance.Load<AudioTable>().Get(id);
		public static AudioTable.Entry DataIn(this AudioIds id, string tablePath) => global::WanFramework.Data.DataSystem.Instance.Load<AudioTable>(tablePath).Get(id);
    }
    #endregion
    
    [System.SerializableAttribute()]
    public class AudioTable : WanFramework.Data.DataTable<AudioTable.Entry> {
        
        public override string TableName {
            get {
                return "AudioTable";
            }
        }
        
        public override void LoadFrom(global::WanFramework.Data.DataTableRawAsset rawAsset) {
            using System.IO.MemoryStream ms = new System.IO.MemoryStream(rawAsset.GetData());
            using System.IO.BinaryReader reader = new System.IO.BinaryReader(ms);
            int entryCount = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
            Game.Data.AudioTable.Entry[] tmpData = new Game.Data.AudioTable.Entry[entryCount];
            for (int i = 0; (i < entryCount); i = (i + 1)) {
                tmpData[i] = new Game.Data.AudioTable.Entry();
                tmpData[i].LoadFrom(reader);
            }
            if ((ms.Length > ms.Position)) {
                throw new System.Exception("Failed to load binary table");
            }
            this.data = tmpData;
        }
        
        public Game.Data.AudioTable.Entry Get(Game.Data.AudioIds id) {
            return ((Game.Data.AudioTable.Entry)(this.Get(((int)(id)))));
        }
        
        [System.SerializableAttribute()]
        public class Entry : WanFramework.Data.DataEntry {
            
            [UnityEngine.SerializeField()]
            private string id;
            
            [UnityEngine.SerializeField()]
            private string track;
            
            [UnityEngine.SerializeField()]
            private string path;
            
            [UnityEngine.SerializeField()]
            private Game.Data.AudioEventType eventType;
            
            [UnityEngine.SerializeField()]
            private float volumeScale;
            
            public string Id {
                get {
                    return this.id;
                }
            }
            
            public string Track {
                get {
                    return this.track;
                }
            }
            
            public string Path {
                get {
                    return this.path;
                }
            }
            
            public Game.Data.AudioEventType EventType {
                get {
                    return this.eventType;
                }
            }
            
            public float VolumeScale {
                get {
                    return this.volumeScale;
                }
            }
            
            public virtual void LoadFrom(System.IO.BinaryReader reader) {
                // System.String this.id
                this.id = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // System.String this.track
                this.track = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // System.String this.path
                this.path = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // Game.Data.AudioEventType this.eventType
                string enum_str_1142745112 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.eventType = System.Enum.Parse<Game.Data.AudioEventType>(enum_str_1142745112);
                // System.Single this.volumeScale
                this.volumeScale = WanFramework.Data.DataTableBinarySerializer.DeserializeSingle(reader);
            }
        }
    }
}
