//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data {
    
    
    public enum BuffIds {
        
        Unknown = 0,
        
        Burning = 1,
        
        Quickness = 2,
        
        Stun = 3,
        
        Calm = 4,
        
        Sturdy = 5,
        
        Reflect = 6,
        
        Rusted = 7,
        
        HighReactivity = 8,
    }
    
    #region 
static
    public class BuffIdsExtensions {
        
		public static BuffTable.Entry Data(this BuffIds id) => global::WanFramework.Data.DataSystem.Instance.Load<BuffTable>().Get(id);
		public static BuffTable.Entry DataIn(this BuffIds id, string tablePath) => global::WanFramework.Data.DataSystem.Instance.Load<BuffTable>(tablePath).Get(id);
    }
    #endregion
    
    [System.SerializableAttribute()]
    public class BuffTable : WanFramework.Data.DataTable<BuffTable.Entry> {
        
        public override string TableName {
            get {
                return "BuffTable";
            }
        }
        
        public override void LoadFrom(global::WanFramework.Data.DataTableRawAsset rawAsset) {
            using System.IO.MemoryStream ms = new System.IO.MemoryStream(rawAsset.GetData());
            using System.IO.BinaryReader reader = new System.IO.BinaryReader(ms);
            int entryCount = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
            Game.Data.BuffTable.Entry[] tmpData = new Game.Data.BuffTable.Entry[entryCount];
            for (int i = 0; (i < entryCount); i = (i + 1)) {
                tmpData[i] = new Game.Data.BuffTable.Entry();
                tmpData[i].LoadFrom(reader);
            }
            if ((ms.Length > ms.Position)) {
                throw new System.Exception("Failed to load binary table");
            }
            this.data = tmpData;
        }
        
        public Game.Data.BuffTable.Entry Get(Game.Data.BuffIds id) {
            return ((Game.Data.BuffTable.Entry)(this.Get(((int)(id)))));
        }
        
        [System.SerializableAttribute()]
        public class Entry : WanFramework.Data.DataEntry {
            
            [UnityEngine.SerializeField()]
            private string id;
            
            [UnityEngine.SerializeField()]
            private Game.Data.LocalizeIds name;
            
            [UnityEngine.SerializeField()]
            private Game.Data.LocalizeIds desc;
            
            [UnityEngine.SerializeField()]
            private int stackMaximum;
            
            [UnityEngine.SerializeField()]
            private bool buffDecreaseAbility;
            
            [UnityEngine.SerializeField()]
            private bool buffDispelAbility;
            
            [UnityEngine.SerializeField()]
            private string prefab;
            
            public string Id {
                get {
                    return this.id;
                }
            }
            
            public Game.Data.LocalizeIds Name {
                get {
                    return this.name;
                }
            }
            
            public Game.Data.LocalizeIds Desc {
                get {
                    return this.desc;
                }
            }
            
            public int StackMaximum {
                get {
                    return this.stackMaximum;
                }
            }
            
            public bool BuffDecreaseAbility {
                get {
                    return this.buffDecreaseAbility;
                }
            }
            
            public bool BuffDispelAbility {
                get {
                    return this.buffDispelAbility;
                }
            }
            
            public string Prefab {
                get {
                    return this.prefab;
                }
            }
            
            public virtual void LoadFrom(System.IO.BinaryReader reader) {
                // System.String this.id
                this.id = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // Game.Data.LocalizeIds this.name
                string enum_str_795507139 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.name = System.Enum.Parse<Game.Data.LocalizeIds>(enum_str_795507139);
                // Game.Data.LocalizeIds this.desc
                string enum_str_420994787 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.desc = System.Enum.Parse<Game.Data.LocalizeIds>(enum_str_420994787);
                // System.Int32 this.stackMaximum
                this.stackMaximum = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                // System.Boolean this.buffDecreaseAbility
                this.buffDecreaseAbility = WanFramework.Data.DataTableBinarySerializer.DeserializeBool(reader);
                // System.Boolean this.buffDispelAbility
                this.buffDispelAbility = WanFramework.Data.DataTableBinarySerializer.DeserializeBool(reader);
                // System.String this.prefab
                this.prefab = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
            }
        }
    }
}
