//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data {
    
    
    public enum BuffPoolIds {
        
        Empty = 0,
        
        Level1_Buff_Pool = 1,
        
        Level2_Buff_Pool = 2,
        
        Level3_Buff_Pool = 3,
    }
    
    #region 
static
    public class BuffPoolIdsExtensions {
        
		public static BuffPoolTable.Entry Data(this BuffPoolIds id) => global::WanFramework.Data.DataSystem.Instance.Load<BuffPoolTable>().Get(id);
		public static BuffPoolTable.Entry DataIn(this BuffPoolIds id, string tablePath) => global::WanFramework.Data.DataSystem.Instance.Load<BuffPoolTable>(tablePath).Get(id);
    }
    #endregion
    
    [System.SerializableAttribute()]
    public class BuffPoolTable : WanFramework.Data.DataTable<BuffPoolTable.Entry> {
        
        public override string TableName {
            get {
                return "BuffPoolTable";
            }
        }
        
        public override void LoadFrom(global::WanFramework.Data.DataTableRawAsset rawAsset) {
            using System.IO.MemoryStream ms = new System.IO.MemoryStream(rawAsset.GetData());
            using System.IO.BinaryReader reader = new System.IO.BinaryReader(ms);
            int entryCount = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
            Game.Data.BuffPoolTable.Entry[] tmpData = new Game.Data.BuffPoolTable.Entry[entryCount];
            for (int i = 0; (i < entryCount); i = (i + 1)) {
                tmpData[i] = new Game.Data.BuffPoolTable.Entry();
                tmpData[i].LoadFrom(reader);
            }
            if ((ms.Length > ms.Position)) {
                throw new System.Exception("Failed to load binary table");
            }
            this.data = tmpData;
        }
        
        public Game.Data.BuffPoolTable.Entry Get(Game.Data.BuffPoolIds id) {
            return ((Game.Data.BuffPoolTable.Entry)(this.Get(((int)(id)))));
        }
        
        [System.SerializableAttribute()]
        public class Entry : WanFramework.Data.DataEntry {
            
            [UnityEngine.SerializeField()]
            private string id;
            
            [UnityEngine.SerializeField()]
            private Game.Data.BuffIds[] buffs;
            
            [UnityEngine.SerializeField()]
            private int[] stacks;
            
            [UnityEngine.SerializeField()]
            private int[] weights;
            
            public string Id {
                get {
                    return this.id;
                }
            }
            
            public Game.Data.BuffIds[] Buffs {
                get {
                    return this.buffs;
                }
            }
            
            public int[] Stacks {
                get {
                    return this.stacks;
                }
            }
            
            public int[] Weights {
                get {
                    return this.weights;
                }
            }
            
            public virtual void LoadFrom(System.IO.BinaryReader reader) {
                // System.String this.id
                this.id = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // Game.Data.BuffIds[] this.buffs
                int array_size_325542130 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.buffs = new Game.Data.BuffIds[array_size_325542130];
                for (int array_size_325542130_i = 0; (array_size_325542130_i < array_size_325542130); array_size_325542130_i = (array_size_325542130_i + 1)) {
                    // Game.Data.BuffIds this.buffs[array_size_325542130_i]
                    string enum_str_897755559 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                    this.buffs[array_size_325542130_i] = System.Enum.Parse<Game.Data.BuffIds>(enum_str_897755559);
                }
                // System.Int32[] this.stacks
                int array_size_600545717 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.stacks = new int[array_size_600545717];
                for (int array_size_600545717_i = 0; (array_size_600545717_i < array_size_600545717); array_size_600545717_i = (array_size_600545717_i + 1)) {
                    // System.Int32 this.stacks[array_size_600545717_i]
                    this.stacks[array_size_600545717_i] = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                }
                // System.Int32[] this.weights
                int array_size_1811543207 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.weights = new int[array_size_1811543207];
                for (int array_size_1811543207_i = 0; (array_size_1811543207_i < array_size_1811543207); array_size_1811543207_i = (array_size_1811543207_i + 1)) {
                    // System.Int32 this.weights[array_size_1811543207_i]
                    this.weights[array_size_1811543207_i] = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                }
            }
        }
    }
}
