//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data {
    
    
    public enum CardIds {
        
        Unknown = 0,
        
        T01 = 1,
        
        T02 = 2,
        
        T03 = 3,
        
        B01 = 4,
        
        B02 = 5,
        
        F100 = 6,
        
        F101 = 7,
        
        F102 = 8,
        
        F103 = 9,
        
        F104 = 10,
        
        F105 = 11,
        
        F106 = 12,
        
        F107 = 13,
        
        F108 = 14,
        
        F109 = 15,
        
        F110 = 16,
        
        F111 = 17,
        
        F112 = 18,
        
        F113 = 19,
        
        F201 = 20,
        
        F202 = 21,
        
        F203 = 22,
        
        F204 = 23,
        
        F205 = 24,
        
        F206 = 25,
        
        F207 = 26,
        
        W100 = 27,
        
        W101 = 28,
        
        W102 = 29,
        
        W103 = 30,
        
        W104 = 31,
        
        W105 = 32,
        
        W106 = 33,
        
        W107 = 34,
        
        W108 = 35,
        
        W109 = 36,
        
        W110 = 37,
        
        W111 = 38,
        
        W112 = 39,
        
        W113 = 40,
        
        W201 = 41,
        
        W202 = 42,
        
        W203 = 43,
        
        W204 = 44,
        
        W205 = 45,
        
        W206 = 46,
        
        W207 = 47,
        
        E100 = 48,
        
        E101 = 49,
        
        E102 = 50,
        
        E103 = 51,
        
        E104 = 52,
        
        E105 = 53,
        
        E106 = 54,
        
        E107 = 55,
        
        E108 = 56,
        
        E109 = 57,
        
        E110 = 58,
        
        E111 = 59,
        
        E112 = 60,
        
        E113 = 61,
        
        E201 = 62,
        
        E202 = 63,
        
        E203 = 64,
        
        E204 = 65,
        
        E205 = 66,
        
        E206 = 67,
        
        E207 = 68,
        
        FW100 = 69,
        
        FW101 = 70,
        
        FW102 = 71,
        
        FW103 = 72,
        
        FW104 = 73,
        
        FW105 = 74,
        
        FW106 = 75,
        
        FW201 = 76,
        
        FW202 = 77,
        
        FW203 = 78,
        
        FW204 = 79,
        
        FW205 = 80,
    }
    
    #region 
static
    public class CardIdsExtensions {
        
		public static CardTable.Entry Data(this CardIds id) => global::WanFramework.Data.DataSystem.Instance.Load<CardTable>().Get(id);
		public static CardTable.Entry DataIn(this CardIds id, string tablePath) => global::WanFramework.Data.DataSystem.Instance.Load<CardTable>(tablePath).Get(id);
    }
    #endregion
    
    [System.SerializableAttribute()]
    public class CardTable : WanFramework.Data.DataTable<CardTable.Entry> {
        
        public override string TableName {
            get {
                return "CardTable";
            }
        }
        
        public override void LoadFrom(global::WanFramework.Data.DataTableRawAsset rawAsset) {
            using System.IO.MemoryStream ms = new System.IO.MemoryStream(rawAsset.GetData());
            using System.IO.BinaryReader reader = new System.IO.BinaryReader(ms);
            int entryCount = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
            Game.Data.CardTable.Entry[] tmpData = new Game.Data.CardTable.Entry[entryCount];
            for (int i = 0; (i < entryCount); i = (i + 1)) {
                tmpData[i] = new Game.Data.CardTable.Entry();
                tmpData[i].LoadFrom(reader);
            }
            if ((ms.Length > ms.Position)) {
                throw new System.Exception("Failed to load binary table");
            }
            this.data = tmpData;
        }
        
        public Game.Data.CardTable.Entry Get(Game.Data.CardIds id) {
            return ((Game.Data.CardTable.Entry)(this.Get(((int)(id)))));
        }
        
        [System.SerializableAttribute()]
        public class Entry : WanFramework.Data.DataEntry {
            
            [UnityEngine.SerializeField()]
            private string id;
            
            [UnityEngine.SerializeField()]
            private Game.Data.LocalizeIds name;
            
            [UnityEngine.SerializeField()]
            private string icon;
            
            [UnityEngine.SerializeField()]
            private Game.Data.CardLabel[] label;
            
            [UnityEngine.SerializeField()]
            private Game.Data.CardBaseType type;
            
            [UnityEngine.SerializeField()]
            private bool[] pool;
            
            [UnityEngine.SerializeField()]
            private Game.Data.CardRarity rarity;
            
            [UnityEngine.SerializeField()]
            private int[] cost;
            
            [UnityEngine.SerializeField()]
            private int value;
            
            [UnityEngine.SerializeField()]
            private int[] effectValue;
            
            [UnityEngine.SerializeField()]
            private Game.Data.EffectIds[] effects;
            
            public string Id {
                get {
                    return this.id;
                }
            }
            
            public Game.Data.LocalizeIds Name {
                get {
                    return this.name;
                }
            }
            
            public string Icon {
                get {
                    return this.icon;
                }
            }
            
            public Game.Data.CardLabel[] Label {
                get {
                    return this.label;
                }
            }
            
            public Game.Data.CardBaseType Type {
                get {
                    return this.type;
                }
            }
            
            public bool[] Pool {
                get {
                    return this.pool;
                }
            }
            
            public Game.Data.CardRarity Rarity {
                get {
                    return this.rarity;
                }
            }
            
            public int[] Cost {
                get {
                    return this.cost;
                }
            }
            
            public int Value {
                get {
                    return this.value;
                }
            }
            
            public int[] EffectValue {
                get {
                    return this.effectValue;
                }
            }
            
            public Game.Data.EffectIds[] Effects {
                get {
                    return this.effects;
                }
            }
            
            public virtual void LoadFrom(System.IO.BinaryReader reader) {
                // System.String this.id
                this.id = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // Game.Data.LocalizeIds this.name
                string enum_str_795507139 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.name = System.Enum.Parse<Game.Data.LocalizeIds>(enum_str_795507139);
                // System.String this.icon
                this.icon = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // Game.Data.CardLabel[] this.label
                int array_size_1730579202 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.label = new Game.Data.CardLabel[array_size_1730579202];
                for (int array_size_1730579202_i = 0; (array_size_1730579202_i < array_size_1730579202); array_size_1730579202_i = (array_size_1730579202_i + 1)) {
                    // Game.Data.CardLabel this.label[array_size_1730579202_i]
                    string enum_str_1635008626 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                    this.label[array_size_1730579202_i] = System.Enum.Parse<Game.Data.CardLabel>(enum_str_1635008626);
                }
                // Game.Data.CardBaseType this.type
                string enum_str_1756534860 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.type = System.Enum.Parse<Game.Data.CardBaseType>(enum_str_1756534860);
                // System.Boolean[] this.pool
                int array_size_145576006 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.pool = new bool[array_size_145576006];
                for (int array_size_145576006_i = 0; (array_size_145576006_i < array_size_145576006); array_size_145576006_i = (array_size_145576006_i + 1)) {
                    // System.Boolean this.pool[array_size_145576006_i]
                    this.pool[array_size_145576006_i] = WanFramework.Data.DataTableBinarySerializer.DeserializeBool(reader);
                }
                // Game.Data.CardRarity this.rarity
                string enum_str_1502541063 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.rarity = System.Enum.Parse<Game.Data.CardRarity>(enum_str_1502541063);
                // System.Int32[] this.cost
                int array_size_284818035 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.cost = new int[array_size_284818035];
                for (int array_size_284818035_i = 0; (array_size_284818035_i < array_size_284818035); array_size_284818035_i = (array_size_284818035_i + 1)) {
                    // System.Int32 this.cost[array_size_284818035_i]
                    this.cost[array_size_284818035_i] = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                }
                // System.Int32 this.value
                this.value = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                // System.Int32[] this.effectValue
                int array_size_950724954 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.effectValue = new int[array_size_950724954];
                for (int array_size_950724954_i = 0; (array_size_950724954_i < array_size_950724954); array_size_950724954_i = (array_size_950724954_i + 1)) {
                    // System.Int32 this.effectValue[array_size_950724954_i]
                    this.effectValue[array_size_950724954_i] = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                }
                // Game.Data.EffectIds[] this.effects
                int array_size_2045679166 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.effects = new Game.Data.EffectIds[array_size_2045679166];
                for (int array_size_2045679166_i = 0; (array_size_2045679166_i < array_size_2045679166); array_size_2045679166_i = (array_size_2045679166_i + 1)) {
                    // Game.Data.EffectIds this.effects[array_size_2045679166_i]
                    string enum_str_846850632 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                    this.effects[array_size_2045679166_i] = System.Enum.Parse<Game.Data.EffectIds>(enum_str_846850632);
                }
            }
        }
    }
}
