//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data {
    
    
    public enum CharacterIds {
        
        Unknown = 0,
        
        Empty = 1,
        
        Fire = 2,
        
        Water = 3,
        
        Earth = 4,
        
        FireWater = 5,
    }
    
    #region 
static
    public class CharacterIdsExtensions {
        
		public static CharacterTable.Entry Data(this CharacterIds id) => global::WanFramework.Data.DataSystem.Instance.Load<CharacterTable>().Get(id);
		public static CharacterTable.Entry DataIn(this CharacterIds id, string tablePath) => global::WanFramework.Data.DataSystem.Instance.Load<CharacterTable>(tablePath).Get(id);
    }
    #endregion
    
    [System.SerializableAttribute()]
    public class CharacterTable : WanFramework.Data.DataTable<CharacterTable.Entry> {
        
        public override string TableName {
            get {
                return "CharacterTable";
            }
        }
        
        public override void LoadFrom(global::WanFramework.Data.DataTableRawAsset rawAsset) {
            using System.IO.MemoryStream ms = new System.IO.MemoryStream(rawAsset.GetData());
            using System.IO.BinaryReader reader = new System.IO.BinaryReader(ms);
            int entryCount = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
            Game.Data.CharacterTable.Entry[] tmpData = new Game.Data.CharacterTable.Entry[entryCount];
            for (int i = 0; (i < entryCount); i = (i + 1)) {
                tmpData[i] = new Game.Data.CharacterTable.Entry();
                tmpData[i].LoadFrom(reader);
            }
            if ((ms.Length > ms.Position)) {
                throw new System.Exception("Failed to load binary table");
            }
            this.data = tmpData;
        }
        
        public Game.Data.CharacterTable.Entry Get(Game.Data.CharacterIds id) {
            return ((Game.Data.CharacterTable.Entry)(this.Get(((int)(id)))));
        }
        
        [System.SerializableAttribute()]
        public class Entry : WanFramework.Data.DataEntry {
            
            [UnityEngine.SerializeField()]
            private string id;
            
            [UnityEngine.SerializeField()]
            private Game.Data.LocalizeIds name;
            
            [UnityEngine.SerializeField()]
            private Game.Data.LocalizeIds desc;
            
            [UnityEngine.SerializeField()]
            private bool[] charElemental;
            
            [UnityEngine.SerializeField()]
            private int[] resMax;
            
            [UnityEngine.SerializeField()]
            private int initialDraws;
            
            [UnityEngine.SerializeField()]
            private int surgeThreshold;
            
            [UnityEngine.SerializeField()]
            private Game.Data.CardIds[] initialCards;
            
            public string Id {
                get {
                    return this.id;
                }
            }
            
            public Game.Data.LocalizeIds Name {
                get {
                    return this.name;
                }
            }
            
            public Game.Data.LocalizeIds Desc {
                get {
                    return this.desc;
                }
            }
            
            public bool[] CharElemental {
                get {
                    return this.charElemental;
                }
            }
            
            public int[] ResMax {
                get {
                    return this.resMax;
                }
            }
            
            public int InitialDraws {
                get {
                    return this.initialDraws;
                }
            }
            
            public int SurgeThreshold {
                get {
                    return this.surgeThreshold;
                }
            }
            
            public Game.Data.CardIds[] InitialCards {
                get {
                    return this.initialCards;
                }
            }
            
            public virtual void LoadFrom(System.IO.BinaryReader reader) {
                // System.String this.id
                this.id = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // Game.Data.LocalizeIds this.name
                string enum_str_795507139 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.name = System.Enum.Parse<Game.Data.LocalizeIds>(enum_str_795507139);
                // Game.Data.LocalizeIds this.desc
                string enum_str_420994787 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.desc = System.Enum.Parse<Game.Data.LocalizeIds>(enum_str_420994787);
                // System.Boolean[] this.charElemental
                int array_size_217448249 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.charElemental = new bool[array_size_217448249];
                for (int array_size_217448249_i = 0; (array_size_217448249_i < array_size_217448249); array_size_217448249_i = (array_size_217448249_i + 1)) {
                    // System.Boolean this.charElemental[array_size_217448249_i]
                    this.charElemental[array_size_217448249_i] = WanFramework.Data.DataTableBinarySerializer.DeserializeBool(reader);
                }
                // System.Int32[] this.resMax
                int array_size_1179284892 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.resMax = new int[array_size_1179284892];
                for (int array_size_1179284892_i = 0; (array_size_1179284892_i < array_size_1179284892); array_size_1179284892_i = (array_size_1179284892_i + 1)) {
                    // System.Int32 this.resMax[array_size_1179284892_i]
                    this.resMax[array_size_1179284892_i] = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                }
                // System.Int32 this.initialDraws
                this.initialDraws = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                // System.Int32 this.surgeThreshold
                this.surgeThreshold = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                // Game.Data.CardIds[] this.initialCards
                int array_size_980130277 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.initialCards = new Game.Data.CardIds[array_size_980130277];
                for (int array_size_980130277_i = 0; (array_size_980130277_i < array_size_980130277); array_size_980130277_i = (array_size_980130277_i + 1)) {
                    // Game.Data.CardIds this.initialCards[array_size_980130277_i]
                    string enum_str_273191330 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                    this.initialCards[array_size_980130277_i] = System.Enum.Parse<Game.Data.CardIds>(enum_str_273191330);
                }
            }
        }
    }
}
