//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data {
    
    
    public enum EffectIds {
        
        Unknown = 0,
        
        Damage = 1,
        
        Damage_Self = 2,
        
        Heal = 3,
        
        Draw = 4,
        
        Recycle = 5,
        
        Discard = 6,
        
        Neutralize = 7,
        
        Catalyze = 8,
        
        Elemental_Fire = 9,
        
        Elemental_Water = 10,
        
        Elemental_Earth = 11,
        
        Elemental_Air = 12,
        
        Buff_Burn_Enemy = 13,
        
        Buff_Burn_Self = 14,
        
        Idle = 15,
        
        Scaling = 16,
        
        LED_Water = 17,
        
        Ignite = 18,
        
        Buff_Calm_Self = 19,
        
        Buff_Quickness_Self = 20,
        
        Buff_Stun_Enemy = 21,
        
        Buff_Sturdy_Self = 22,
        
        Buff_Reflect_Self = 23,
        
        Buff_Reflect_Enemy = 24,
        
        Damage_Surge = 25,
        
        Damage_Self_Surge = 26,
        
        Heal_Surge = 27,
        
        Draw_Surge = 28,
        
        Damage_Madness = 29,
        
        Damage_Self_Madness = 30,
        
        Heal_Madness = 31,
        
        Draw_Madness = 32,
        
        Discard_Madness = 33,
        
        Elemental_Water_Madness = 34,
        
        Buff_Stun_Enemy_Madness = 35,
        
        Damage_Unstable = 36,
        
        Damage_Self_Unstable = 37,
        
        Heal_Unstable = 38,
        
        Draw_Unstable = 39,
        
        Damage_Cooldown = 40,
        
        Draw_Cooldown = 41,
        
        Ignite_Cooldown = 42,
        
        Calm_Cooldown = 43,
        
        Damage_Peace = 44,
        
        Draw_Peace = 45,
        
        Quickness_Peace = 46,
        
        Calm_Peace = 47,
        
        Draw_Focus = 48,
        
        Damage_Focus = 49,
        
        Damage_Windborne = 50,
    }
    
    #region 
static
    public class EffectIdsExtensions {
        
		public static EffectTable.Entry Data(this EffectIds id) => global::WanFramework.Data.DataSystem.Instance.Load<EffectTable>().Get(id);
		public static EffectTable.Entry DataIn(this EffectIds id, string tablePath) => global::WanFramework.Data.DataSystem.Instance.Load<EffectTable>(tablePath).Get(id);
    }
    #endregion
    
    [System.SerializableAttribute()]
    public class EffectTable : WanFramework.Data.DataTable<EffectTable.Entry> {
        
        public override string TableName {
            get {
                return "EffectTable";
            }
        }
        
        public override void LoadFrom(global::WanFramework.Data.DataTableRawAsset rawAsset) {
            using System.IO.MemoryStream ms = new System.IO.MemoryStream(rawAsset.GetData());
            using System.IO.BinaryReader reader = new System.IO.BinaryReader(ms);
            int entryCount = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
            Game.Data.EffectTable.Entry[] tmpData = new Game.Data.EffectTable.Entry[entryCount];
            for (int i = 0; (i < entryCount); i = (i + 1)) {
                tmpData[i] = new Game.Data.EffectTable.Entry();
                tmpData[i].LoadFrom(reader);
            }
            if ((ms.Length > ms.Position)) {
                throw new System.Exception("Failed to load binary table");
            }
            this.data = tmpData;
        }
        
        public Game.Data.EffectTable.Entry Get(Game.Data.EffectIds id) {
            return ((Game.Data.EffectTable.Entry)(this.Get(((int)(id)))));
        }
        
        [System.SerializableAttribute()]
        public class Entry : WanFramework.Data.DataEntry {
            
            [UnityEngine.SerializeField()]
            private string id;
            
            [UnityEngine.SerializeField()]
            private Game.Data.LocalizeIds desc;
            
            [UnityEngine.SerializeField()]
            private int maximum;
            
            [UnityEngine.SerializeField()]
            private Game.Data.CardCondition condition;
            
            public string Id {
                get {
                    return this.id;
                }
            }
            
            public Game.Data.LocalizeIds Desc {
                get {
                    return this.desc;
                }
            }
            
            public int Maximum {
                get {
                    return this.maximum;
                }
            }
            
            public Game.Data.CardCondition Condition {
                get {
                    return this.condition;
                }
            }
            
            public virtual void LoadFrom(System.IO.BinaryReader reader) {
                // System.String this.id
                this.id = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // Game.Data.LocalizeIds this.desc
                string enum_str_420994787 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.desc = System.Enum.Parse<Game.Data.LocalizeIds>(enum_str_420994787);
                // System.Int32 this.maximum
                this.maximum = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                // Game.Data.CardCondition this.condition
                string enum_str_787549961 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.condition = System.Enum.Parse<Game.Data.CardCondition>(enum_str_787549961);
            }
        }
    }
}
