//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data {
    
    
    public enum EnemyPoolIds {
        
        Empty = 0,
        
        Level1_Enemy_Pool = 1,
        
        Level1_Enemy_Pool_Boss = 2,
        
        Level2_Enemy_Pool = 3,
        
        Level2_Enemy_Pool_Boss = 4,
        
        Level3_Enemy_Pool = 5,
        
        Level3_Enemy_Pool_Boss = 6,
        
        Level4_Enemy_Pool = 7,
        
        Level4_Enemy_Pool_Boss = 8,
        
        Level5_Enemy_Pool = 9,
        
        Level5_Enemy_Pool_Boss = 10,
        
        Infinite_Enemy_Pool = 11,
    }
    
    #region 
static
    public class EnemyPoolIdsExtensions {
        
		public static EnemyPoolTable.Entry Data(this EnemyPoolIds id) => global::WanFramework.Data.DataSystem.Instance.Load<EnemyPoolTable>().Get(id);
		public static EnemyPoolTable.Entry DataIn(this EnemyPoolIds id, string tablePath) => global::WanFramework.Data.DataSystem.Instance.Load<EnemyPoolTable>(tablePath).Get(id);
    }
    #endregion
    
    [System.SerializableAttribute()]
    public class EnemyPoolTable : WanFramework.Data.DataTable<EnemyPoolTable.Entry> {
        
        public override string TableName {
            get {
                return "EnemyPoolTable";
            }
        }
        
        public override void LoadFrom(global::WanFramework.Data.DataTableRawAsset rawAsset) {
            using System.IO.MemoryStream ms = new System.IO.MemoryStream(rawAsset.GetData());
            using System.IO.BinaryReader reader = new System.IO.BinaryReader(ms);
            int entryCount = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
            Game.Data.EnemyPoolTable.Entry[] tmpData = new Game.Data.EnemyPoolTable.Entry[entryCount];
            for (int i = 0; (i < entryCount); i = (i + 1)) {
                tmpData[i] = new Game.Data.EnemyPoolTable.Entry();
                tmpData[i].LoadFrom(reader);
            }
            if ((ms.Length > ms.Position)) {
                throw new System.Exception("Failed to load binary table");
            }
            this.data = tmpData;
        }
        
        public Game.Data.EnemyPoolTable.Entry Get(Game.Data.EnemyPoolIds id) {
            return ((Game.Data.EnemyPoolTable.Entry)(this.Get(((int)(id)))));
        }
        
        [System.SerializableAttribute()]
        public class Entry : WanFramework.Data.DataEntry {
            
            [UnityEngine.SerializeField()]
            private string id;
            
            [UnityEngine.SerializeField()]
            private Game.Data.EnemyIds[] enemies;
            
            [UnityEngine.SerializeField()]
            private int[] weights;
            
            public string Id {
                get {
                    return this.id;
                }
            }
            
            public Game.Data.EnemyIds[] Enemies {
                get {
                    return this.enemies;
                }
            }
            
            public int[] Weights {
                get {
                    return this.weights;
                }
            }
            
            public virtual void LoadFrom(System.IO.BinaryReader reader) {
                // System.String this.id
                this.id = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // Game.Data.EnemyIds[] this.enemies
                int array_size_2093241532 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.enemies = new Game.Data.EnemyIds[array_size_2093241532];
                for (int array_size_2093241532_i = 0; (array_size_2093241532_i < array_size_2093241532); array_size_2093241532_i = (array_size_2093241532_i + 1)) {
                    // Game.Data.EnemyIds this.enemies[array_size_2093241532_i]
                    string enum_str_334625271 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                    this.enemies[array_size_2093241532_i] = System.Enum.Parse<Game.Data.EnemyIds>(enum_str_334625271);
                }
                // System.Int32[] this.weights
                int array_size_1811543207 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.weights = new int[array_size_1811543207];
                for (int array_size_1811543207_i = 0; (array_size_1811543207_i < array_size_1811543207); array_size_1811543207_i = (array_size_1811543207_i + 1)) {
                    // System.Int32 this.weights[array_size_1811543207_i]
                    this.weights[array_size_1811543207_i] = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                }
            }
        }
    }
}
