//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data {
    
    
    public enum EnemyIds {
        
        Unknown = 0,
        
        Test = 1,
        
        TestBoss = 2,
        
        Test2 = 3,
        
        TestBoss2 = 4,
        
        Test3 = 5,
        
        TestBoss3 = 6,
        
        Test4 = 7,
        
        TestBoss4 = 8,
        
        Test5 = 9,
        
        TestBoss5 = 10,
        
        Infinite_Enemy = 11,
    }
    
    #region 
static
    public class EnemyIdsExtensions {
        
		public static EnemyTable.Entry Data(this EnemyIds id) => global::WanFramework.Data.DataSystem.Instance.Load<EnemyTable>().Get(id);
		public static EnemyTable.Entry DataIn(this EnemyIds id, string tablePath) => global::WanFramework.Data.DataSystem.Instance.Load<EnemyTable>(tablePath).Get(id);
    }
    #endregion
    
    [System.SerializableAttribute()]
    public class EnemyTable : WanFramework.Data.DataTable<EnemyTable.Entry> {
        
        public override string TableName {
            get {
                return "EnemyTable";
            }
        }
        
        public override void LoadFrom(global::WanFramework.Data.DataTableRawAsset rawAsset) {
            using System.IO.MemoryStream ms = new System.IO.MemoryStream(rawAsset.GetData());
            using System.IO.BinaryReader reader = new System.IO.BinaryReader(ms);
            int entryCount = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
            Game.Data.EnemyTable.Entry[] tmpData = new Game.Data.EnemyTable.Entry[entryCount];
            for (int i = 0; (i < entryCount); i = (i + 1)) {
                tmpData[i] = new Game.Data.EnemyTable.Entry();
                tmpData[i].LoadFrom(reader);
            }
            if ((ms.Length > ms.Position)) {
                throw new System.Exception("Failed to load binary table");
            }
            this.data = tmpData;
        }
        
        public Game.Data.EnemyTable.Entry Get(Game.Data.EnemyIds id) {
            return ((Game.Data.EnemyTable.Entry)(this.Get(((int)(id)))));
        }
        
        [System.SerializableAttribute()]
        public class Entry : WanFramework.Data.DataEntry {
            
            [UnityEngine.SerializeField()]
            private string id;
            
            [UnityEngine.SerializeField()]
            private Game.Data.LocalizeIds name;
            
            [UnityEngine.SerializeField()]
            private Game.Data.LocalizeIds desc;
            
            [UnityEngine.SerializeField()]
            private int[] enemyAttributes;
            
            [UnityEngine.SerializeField()]
            private string prefab;
            
            public string Id {
                get {
                    return this.id;
                }
            }
            
            public Game.Data.LocalizeIds Name {
                get {
                    return this.name;
                }
            }
            
            public Game.Data.LocalizeIds Desc {
                get {
                    return this.desc;
                }
            }
            
            public int[] EnemyAttributes {
                get {
                    return this.enemyAttributes;
                }
            }
            
            public string Prefab {
                get {
                    return this.prefab;
                }
            }
            
            public virtual void LoadFrom(System.IO.BinaryReader reader) {
                // System.String this.id
                this.id = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // Game.Data.LocalizeIds this.name
                string enum_str_795507139 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.name = System.Enum.Parse<Game.Data.LocalizeIds>(enum_str_795507139);
                // Game.Data.LocalizeIds this.desc
                string enum_str_420994787 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.desc = System.Enum.Parse<Game.Data.LocalizeIds>(enum_str_420994787);
                // System.Int32[] this.enemyAttributes
                int array_size_69194739 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.enemyAttributes = new int[array_size_69194739];
                for (int array_size_69194739_i = 0; (array_size_69194739_i < array_size_69194739); array_size_69194739_i = (array_size_69194739_i + 1)) {
                    // System.Int32 this.enemyAttributes[array_size_69194739_i]
                    this.enemyAttributes[array_size_69194739_i] = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                }
                // System.String this.prefab
                this.prefab = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
            }
        }
    }
}
