//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data {
    
    
    public enum LevelIds {
        
        Unknown = 0,
        
        Map1_Entry = 1,
        
        Tutorial = 2,
        
        Level1 = 3,
        
        Level2 = 4,
        
        Level3 = 5,
        
        Level4 = 6,
        
        Level5 = 7,
        
        Level_Infinite_Entry = 8,
        
        Level_Infinite = 9,
    }
    
    #region 
static
    public class LevelIdsExtensions {
        
		public static LevelTable.Entry Data(this LevelIds id) => global::WanFramework.Data.DataSystem.Instance.Load<LevelTable>().Get(id);
		public static LevelTable.Entry DataIn(this LevelIds id, string tablePath) => global::WanFramework.Data.DataSystem.Instance.Load<LevelTable>(tablePath).Get(id);
    }
    #endregion
    
    [System.SerializableAttribute()]
    public class LevelTable : WanFramework.Data.DataTable<LevelTable.Entry> {
        
        public override string TableName {
            get {
                return "LevelTable";
            }
        }
        
        public override void LoadFrom(global::WanFramework.Data.DataTableRawAsset rawAsset) {
            using System.IO.MemoryStream ms = new System.IO.MemoryStream(rawAsset.GetData());
            using System.IO.BinaryReader reader = new System.IO.BinaryReader(ms);
            int entryCount = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
            Game.Data.LevelTable.Entry[] tmpData = new Game.Data.LevelTable.Entry[entryCount];
            for (int i = 0; (i < entryCount); i = (i + 1)) {
                tmpData[i] = new Game.Data.LevelTable.Entry();
                tmpData[i].LoadFrom(reader);
            }
            if ((ms.Length > ms.Position)) {
                throw new System.Exception("Failed to load binary table");
            }
            this.data = tmpData;
        }
        
        public Game.Data.LevelTable.Entry Get(Game.Data.LevelIds id) {
            return ((Game.Data.LevelTable.Entry)(this.Get(((int)(id)))));
        }
        
        [System.SerializableAttribute()]
        public class Entry : WanFramework.Data.DataEntry {
            
            [UnityEngine.SerializeField()]
            private string id;
            
            [UnityEngine.SerializeField()]
            private Game.Data.LocalizeIds name;
            
            [UnityEngine.SerializeField()]
            private Game.Data.LocalizeIds desc;
            
            [UnityEngine.SerializeField()]
            private int par;
            
            [UnityEngine.SerializeField()]
            private Game.Data.LocalizeIds bossDesc;
            
            [UnityEngine.SerializeField()]
            private Game.Data.BuffPoolIds bossBuffPool;
            
            [UnityEngine.SerializeField()]
            private int bossBuffCount;
            
            [UnityEngine.SerializeField()]
            private Game.Data.BuffPoolIds playerBuffPool;
            
            [UnityEngine.SerializeField()]
            private int playerBuffCount;
            
            [UnityEngine.SerializeField()]
            private Game.Data.LevelPoolIds nextLevelPool;
            
            [UnityEngine.SerializeField()]
            private Game.Data.EnemyPoolIds normalBattleEnemyPool;
            
            [UnityEngine.SerializeField()]
            private Game.Data.EnemyPoolIds bossEnemyPool;
            
            [UnityEngine.SerializeField()]
            private bool hasNormalBattle;
            
            [UnityEngine.SerializeField()]
            private bool hasShop;
            
            [UnityEngine.SerializeField()]
            private bool hasBoss;
            
            [UnityEngine.SerializeField()]
            private float healthAdditionScale;
            
            [UnityEngine.SerializeField()]
            private float atkAdditionScale;
            
            public string Id {
                get {
                    return this.id;
                }
            }
            
            public Game.Data.LocalizeIds Name {
                get {
                    return this.name;
                }
            }
            
            public Game.Data.LocalizeIds Desc {
                get {
                    return this.desc;
                }
            }
            
            public int Par {
                get {
                    return this.par;
                }
            }
            
            public Game.Data.LocalizeIds BossDesc {
                get {
                    return this.bossDesc;
                }
            }
            
            public Game.Data.BuffPoolIds BossBuffPool {
                get {
                    return this.bossBuffPool;
                }
            }
            
            public int BossBuffCount {
                get {
                    return this.bossBuffCount;
                }
            }
            
            public Game.Data.BuffPoolIds PlayerBuffPool {
                get {
                    return this.playerBuffPool;
                }
            }
            
            public int PlayerBuffCount {
                get {
                    return this.playerBuffCount;
                }
            }
            
            public Game.Data.LevelPoolIds NextLevelPool {
                get {
                    return this.nextLevelPool;
                }
            }
            
            public Game.Data.EnemyPoolIds NormalBattleEnemyPool {
                get {
                    return this.normalBattleEnemyPool;
                }
            }
            
            public Game.Data.EnemyPoolIds BossEnemyPool {
                get {
                    return this.bossEnemyPool;
                }
            }
            
            public bool HasNormalBattle {
                get {
                    return this.hasNormalBattle;
                }
            }
            
            public bool HasShop {
                get {
                    return this.hasShop;
                }
            }
            
            public bool HasBoss {
                get {
                    return this.hasBoss;
                }
            }
            
            public float HealthAdditionScale {
                get {
                    return this.healthAdditionScale;
                }
            }
            
            public float AtkAdditionScale {
                get {
                    return this.atkAdditionScale;
                }
            }
            
            public virtual void LoadFrom(System.IO.BinaryReader reader) {
                // System.String this.id
                this.id = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // Game.Data.LocalizeIds this.name
                string enum_str_795507139 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.name = System.Enum.Parse<Game.Data.LocalizeIds>(enum_str_795507139);
                // Game.Data.LocalizeIds this.desc
                string enum_str_420994787 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.desc = System.Enum.Parse<Game.Data.LocalizeIds>(enum_str_420994787);
                // System.Int32 this.par
                this.par = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                // Game.Data.LocalizeIds this.bossDesc
                string enum_str_225327428 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.bossDesc = System.Enum.Parse<Game.Data.LocalizeIds>(enum_str_225327428);
                // Game.Data.BuffPoolIds this.bossBuffPool
                string enum_str_613520254 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.bossBuffPool = System.Enum.Parse<Game.Data.BuffPoolIds>(enum_str_613520254);
                // System.Int32 this.bossBuffCount
                this.bossBuffCount = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                // Game.Data.BuffPoolIds this.playerBuffPool
                string enum_str_912853910 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.playerBuffPool = System.Enum.Parse<Game.Data.BuffPoolIds>(enum_str_912853910);
                // System.Int32 this.playerBuffCount
                this.playerBuffCount = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                // Game.Data.LevelPoolIds this.nextLevelPool
                string enum_str_1283412777 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.nextLevelPool = System.Enum.Parse<Game.Data.LevelPoolIds>(enum_str_1283412777);
                // Game.Data.EnemyPoolIds this.normalBattleEnemyPool
                string enum_str_821768707 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.normalBattleEnemyPool = System.Enum.Parse<Game.Data.EnemyPoolIds>(enum_str_821768707);
                // Game.Data.EnemyPoolIds this.bossEnemyPool
                string enum_str_1647982111 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.bossEnemyPool = System.Enum.Parse<Game.Data.EnemyPoolIds>(enum_str_1647982111);
                // System.Boolean this.hasNormalBattle
                this.hasNormalBattle = WanFramework.Data.DataTableBinarySerializer.DeserializeBool(reader);
                // System.Boolean this.hasShop
                this.hasShop = WanFramework.Data.DataTableBinarySerializer.DeserializeBool(reader);
                // System.Boolean this.hasBoss
                this.hasBoss = WanFramework.Data.DataTableBinarySerializer.DeserializeBool(reader);
                // System.Single this.healthAdditionScale
                this.healthAdditionScale = WanFramework.Data.DataTableBinarySerializer.DeserializeSingle(reader);
                // System.Single this.atkAdditionScale
                this.atkAdditionScale = WanFramework.Data.DataTableBinarySerializer.DeserializeSingle(reader);
            }
        }
    }
}
