//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data {
    
    
    public enum LevelPoolIds {
        
        Level_End = 0,
        
        Map1_Entry_Pool = 1,
        
        Level1_Pool = 2,
        
        Level2_Pool = 3,
        
        Level3_Pool = 4,
        
        Level4_Pool = 5,
        
        Level5_Pool = 6,
        
        Infinite_Entry_Pool = 7,
        
        Infinite_Pool = 8,
    }
    
    #region 
static
    public class LevelPoolIdsExtensions {
        
		public static LevelPoolTable.Entry Data(this LevelPoolIds id) => global::WanFramework.Data.DataSystem.Instance.Load<LevelPoolTable>().Get(id);
		public static LevelPoolTable.Entry DataIn(this LevelPoolIds id, string tablePath) => global::WanFramework.Data.DataSystem.Instance.Load<LevelPoolTable>(tablePath).Get(id);
    }
    #endregion
    
    [System.SerializableAttribute()]
    public class LevelPoolTable : WanFramework.Data.DataTable<LevelPoolTable.Entry> {
        
        public override string TableName {
            get {
                return "LevelPoolTable";
            }
        }
        
        public override void LoadFrom(global::WanFramework.Data.DataTableRawAsset rawAsset) {
            using System.IO.MemoryStream ms = new System.IO.MemoryStream(rawAsset.GetData());
            using System.IO.BinaryReader reader = new System.IO.BinaryReader(ms);
            int entryCount = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
            Game.Data.LevelPoolTable.Entry[] tmpData = new Game.Data.LevelPoolTable.Entry[entryCount];
            for (int i = 0; (i < entryCount); i = (i + 1)) {
                tmpData[i] = new Game.Data.LevelPoolTable.Entry();
                tmpData[i].LoadFrom(reader);
            }
            if ((ms.Length > ms.Position)) {
                throw new System.Exception("Failed to load binary table");
            }
            this.data = tmpData;
        }
        
        public Game.Data.LevelPoolTable.Entry Get(Game.Data.LevelPoolIds id) {
            return ((Game.Data.LevelPoolTable.Entry)(this.Get(((int)(id)))));
        }
        
        [System.SerializableAttribute()]
        public class Entry : WanFramework.Data.DataEntry {
            
            [UnityEngine.SerializeField()]
            private string id;
            
            [UnityEngine.SerializeField()]
            private Game.Data.LevelIds[] levels;
            
            [UnityEngine.SerializeField()]
            private int[] weights;
            
            public string Id {
                get {
                    return this.id;
                }
            }
            
            public Game.Data.LevelIds[] Levels {
                get {
                    return this.levels;
                }
            }
            
            public int[] Weights {
                get {
                    return this.weights;
                }
            }
            
            public virtual void LoadFrom(System.IO.BinaryReader reader) {
                // System.String this.id
                this.id = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // Game.Data.LevelIds[] this.levels
                int array_size_1502028883 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.levels = new Game.Data.LevelIds[array_size_1502028883];
                for (int array_size_1502028883_i = 0; (array_size_1502028883_i < array_size_1502028883); array_size_1502028883_i = (array_size_1502028883_i + 1)) {
                    // Game.Data.LevelIds this.levels[array_size_1502028883_i]
                    string enum_str_855755502 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                    this.levels[array_size_1502028883_i] = System.Enum.Parse<Game.Data.LevelIds>(enum_str_855755502);
                }
                // System.Int32[] this.weights
                int array_size_1811543207 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.weights = new int[array_size_1811543207];
                for (int array_size_1811543207_i = 0; (array_size_1811543207_i < array_size_1811543207); array_size_1811543207_i = (array_size_1811543207_i + 1)) {
                    // System.Int32 this.weights[array_size_1811543207_i]
                    this.weights[array_size_1811543207_i] = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                }
            }
        }
    }
}
