//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data {
    
    
    public enum LocalizeIds {
        
        Unknown = 0,
        
        Empty = 1,
        
        UI_Button_Tutorial = 2,
        
        UI_Button_Exit = 3,
        
        UI_Button_NewGame = 4,
        
        UI_Button_Continue = 5,
        
        UI_Button_MainMenu = 6,
        
        UI_Button_SelectElements = 7,
        
        UI_Button_Draw = 8,
        
        UI_Button_Setting = 9,
        
        UI_Button_CardDeck = 10,
        
        UI_Button_Close = 11,
        
        UI_Button_Skip = 12,
        
        UI_Button_Language = 13,
        
        UI_Button_Volume = 14,
        
        UI_Button_CameraShakeSensitivity = 15,
        
        UI_Button_QuickUse = 16,
        
        UI_Button_FullScreen = 17,
        
        UI_Button_SelectRewards = 18,
        
        UI_Button_SelectRareRewards = 19,
        
        UI_Button_ManagePotions = 20,
        
        UI_Mainmenu_Instructor = 21,
        
        UI_Common_SelectFirst = 22,
        
        UI_Error_Elements = 23,
        
        UI_Error_HandCards = 24,
        
        UI_Error_ShopNotEnoughMoney = 25,
        
        UI_Error_ShopNoValSelected = 26,
        
        UI_End_Win_Title = 27,
        
        UI_End_Win_Desc = 28,
        
        UI_End_Lose_Title = 29,
        
        UI_End_Lose_Desc = 30,
        
        UI_Shop_TavernBoard = 31,
        
        UI_Shop_RefreshPrice = 32,
        
        UI_Shop_DeletePrice = 33,
        
        UI_Shop_UpdatePrice = 34,
        
        UI_Shop_EachTime_1 = 35,
        
        UI_Shop_EachTime_2 = 36,
        
        UI_Shop_NextExp = 37,
        
        Card_Separator = 38,
        
        Card_Test = 39,
        
        DiscardTest = 40,
        
        NBPotion = 41,
        
        TestFirePotion = 42,
        
        Branch_Test1 = 43,
        
        Branch_Test2 = 44,
        
        FireElementBottle = 45,
        
        BasicFirePotion = 46,
        
        FirePotion = 47,
        
        PowerPotion = 48,
        
        HeatTherapy = 49,
        
        CatalyzePotion = 50,
        
        ScalePotion = 51,
        
        FlashPotion = 52,
        
        WillOWisp = 53,
        
        BlastPotion = 54,
        
        InternalBurningPotion = 55,
        
        UnstableFirePotion = 56,
        
        EmberPotion = 57,
        
        ExternalBurningPotion = 58,
        
        GreaterFirePotion = 59,
        
        PulsePotion = 60,
        
        Supernova = 61,
        
        MidasPotion = 62,
        
        BottledFireball = 63,
        
        BottledPhoenix = 64,
        
        BottledSimianSpirit = 65,
        
        WaterElementBottle = 66,
        
        BasicWaterPotion = 67,
        
        WaterPotion = 68,
        
        SpeedPotion = 69,
        
        HealPotion = 70,
        
        NeutralizePotion = 71,
        
        CyclePotion = 72,
        
        CalmMindPotion = 73,
        
        EbbPotion = 74,
        
        FlowPotion = 75,
        
        SacredSpringWater = 76,
        
        LamentOfTheWise = 77,
        
        OceanElementBottle = 78,
        
        Tsunami = 79,
        
        EndlessWave = 80,
        
        GreaterWaterPotion = 81,
        
        LionsTears = 82,
        
        ForbiddenDroplet = 83,
        
        BottledSwirl = 84,
        
        BottledOasis = 85,
        
        ConstantFlux = 86,
        
        Ethanol = 87,
        
        Lorazepam = 88,
        
        DryIce = 89,
        
        Ammonia = 90,
        
        ConcentratedNitricAcid = 91,
        
        Dopamine = 92,
        
        Methane = 93,
        
        SodiumBicarbonate = 94,
        
        Trinitrotoluene = 95,
        
        Graphene = 96,
        
        TaqDNAPolymerase = 97,
        
        Chloroform = 98,
        
        EarthElementBottle = 99,
        
        BasicEarthPotion = 100,
        
        EarthPotion = 101,
        
        EarthCorePotion = 102,
        
        VitalityPotion = 103,
        
        IronbonePotion = 104,
        
        ShacklePotion = 105,
        
        ReflectionPotion = 106,
        
        StoneskinPotion = 107,
        
        FocusPotion = 108,
        
        SpikePotion = 109,
        
        EarthPowerPotion = 110,
        
        CrustPotion = 111,
        
        BreathOfEarth = 112,
        
        GreaterEarthPotion = 113,
        
        BreathOfTheWild = 114,
        
        RoarOfTheEarth = 115,
        
        BottledFissure = 116,
        
        BottledSandstorm = 117,
        
        ScorchingSandsPotion = 118,
        
        Bedrock = 119,
        
        AirElementBottle = 120,
        
        BasicAirPotion = 121,
        
        AirPotion = 122,
        
        TailwindPotion = 123,
        
        BreezePotion = 124,
        
        StrongWindPotion = 125,
        
        GustPotion = 126,
        
        TornadoPotion = 127,
        
        HurricanePotion = 128,
        
        ConvectionPotion = 129,
        
        ReactiveGas = 130,
        
        GreaterAirPotion = 131,
        
        SevereConvectionPotion = 132,
        
        FairyWind = 133,
        
        Character_Test = 134,
        
        Enemy_Test = 135,
        
        Character_Defalt = 136,
        
        Character_Defalt_Desc = 137,
        
        Character_Unknown = 138,
        
        Character_Unknown_Desc = 139,
        
        Character_Pyromancer = 140,
        
        Character_Pyromancer_Desc = 141,
        
        Character_Watermancer = 142,
        
        Character_Watermancer_Desc = 143,
        
        Character_Scientist = 144,
        
        Character_Scientist_Desc = 145,
        
        Character_EarthMage = 146,
        
        Character_EarthMage_Desc = 147,
        
        Character_Airbender = 148,
        
        Character_Airbender_Desc = 149,
        
        Buff_Burning = 150,
        
        Buff_Burning_Desc = 151,
        
        Buff_Quickness = 152,
        
        Buff_Quickness_Desc = 153,
        
        Buff_Stun = 154,
        
        Buff_Stun_Desc = 155,
        
        Buff_Calm = 156,
        
        Buff_Calm_Desc = 157,
        
        Buff_Sturdy = 158,
        
        Buff_Sturdy_Desc = 159,
        
        Buff_Reflect = 160,
        
        Buff_Reflect_Desc = 161,
        
        Buff_Rusted = 162,
        
        Buff_Rusted_Desc = 163,
        
        Buff_HighReactivity = 164,
        
        Buff_HighReactivity_Desc = 165,
        
        Level_Unknown = 166,
        
        TutorialLevel_Name = 167,
        
        Level1_Name = 168,
        
        Level1_Desc = 169,
        
        Level2_Name = 170,
        
        Level2_Desc = 171,
        
        Level3_Name = 172,
        
        Level3_Desc = 173,
        
        Level4_Name = 174,
        
        Level4_Desc = 175,
        
        Level5_Name = 176,
        
        Level5_Desc = 177,
        
        Level_Infinite_Name = 178,
        
        Level_Infinite_Desc = 179,
        
        Boss_RustedVessel_Desc = 180,
        
        Boss_HighReactivity_Desc = 181,
        
        Boss_Uncomplete_Desc = 182,
        
        Boss_Infinite_Desc = 183,
        
        Level_Step1_Desc = 184,
        
        Level_Step2_Desc = 185,
        
        Tutorial_Message_Test = 186,
        
        Tutorial_Message_1 = 187,
        
        Tutorial_Message_2 = 188,
        
        Tutorial_Message_3 = 189,
        
        Tutorial_Message_4 = 190,
        
        Tutorial_Message_5 = 191,
        
        Tutorial_Message_6 = 192,
        
        Tutorial_Message_7 = 193,
        
        Tutorial_Message_8 = 194,
        
        Tutorial_Message_9 = 195,
        
        Tutorial_Message_10 = 196,
        
        Tutorial_Message_11 = 197,
        
        Tutorial_Message_11_1 = 198,
        
        Tutorial_Message_11_2 = 199,
        
        Tutorial_Message_11_3 = 200,
        
        Tutorial_Message_12 = 201,
        
        Tutorial_Message_13 = 202,
        
        Tutorial_Message_14 = 203,
        
        Tutorial_Message_15 = 204,
        
        Tutorial_Message_15_1 = 205,
        
        Tutorial_Message_15_2 = 206,
        
        Tutorial_Message_CardDetail_1 = 207,
        
        Tutorial_Message_CardDetail_2 = 208,
        
        Tutorial_Message_16 = 209,
        
        Tutorial_Message_17 = 210,
        
        Tutorial_Message_18 = 211,
        
        Tutorial_Message_19 = 212,
        
        Tutorial_Message_20 = 213,
        
        Tutorial_Message_21 = 214,
        
        Tutorial_Message_22 = 215,
        
        Tutorial_Message_23 = 216,
        
        Tutorial_23_Draw = 217,
        
        Tutorial_Message_23_1 = 218,
        
        Tutorial_Message_23_2 = 219,
        
        Tutorial_Message_23_3 = 220,
        
        Tutorial_Message_23_4 = 221,
        
        Tutorial_Message_24 = 222,
        
        Tutorial_Message_25 = 223,
        
        Tutorial_Message_26 = 224,
        
        Tutorial_Message_27 = 225,
        
        Tutorial_Message_28 = 226,
        
        Tutorial_Message_Branch1 = 227,
        
        Tutorial_Message_Branch2 = 228,
        
        Tutorial_Message_EnterCharaSelection = 229,
        
        Tutorial_Message_EnterCharaSelection_2 = 230,
        
        Tutorial_Message_EnterCharaSelection_3 = 231,
        
        Tutorial_Message_EnterMap = 232,
        
        Tutorial_Message_EnterMap_2 = 233,
        
        Tutorial_Message_EnterMap_3 = 234,
        
        Tutorial_Message_EnterMap_4 = 235,
        
        Tutorial_Message_EnterMap_5 = 236,
        
        Tutorial_Message_EnterMap_6 = 237,
        
        Tutorial_Message_EnterMap_7 = 238,
        
        Tutorial_Message_EnterMap_8 = 239,
        
        Tutorial_Message_Reward_1 = 240,
        
        Tutorial_Message_Reward_2 = 241,
        
        Tutorial_Message_Reward_3 = 242,
        
        Tutorial_Message_Reward_4 = 243,
        
        Tutorial_Message_Reward_5 = 244,
        
        Tutorial_Message_Reward_6 = 245,
        
        Tutorial_Message_HealthBelow25 = 246,
        
        Tutorial_Message_Shop_1 = 247,
        
        Tutorial_Message_Shop_2 = 248,
        
        Tutorial_Message_Shop_3 = 249,
        
        Tutorial_Message_Shop_4 = 250,
        
        Tutorial_Message_Shop_5 = 251,
        
        Tutorial_Message_Shop_6 = 252,
        
        Tutorial_Message_ShopUpdate_1 = 253,
        
        Tutorial_Message_ShopUpdate_2 = 254,
        
        Tutorial_Message_ShopUpdate_3 = 255,
        
        Tutorial_Message_ShopUpdate_4 = 256,
        
        Tutorial_Message_ShopUpdate_5 = 257,
        
        Tutorial_Message_ShopUpdate_6 = 258,
        
        Tutorial_Message_ShopUpdate_7 = 259,
        
        Tutorial_Message_ShopUpdate_8 = 260,
        
        Tutorial_Message_ShopUpdate_9 = 261,
        
        Tutorial_Message_ShopUpdate_10 = 262,
        
        Tutorial_Message_ShopUpdate_11 = 263,
        
        Tutorial_Message_ShopUpdate_12 = 264,
        
        Tutorial_Message_ShopUpdate_13 = 265,
        
        Tutorial_Message_Boss_1 = 266,
        
        Tutorial_Message_Boss_2 = 267,
        
        Tutorial_Message_Boss_3 = 268,
        
        Tutorial_Message_Boss_4 = 269,
        
        Tutorial_Message_Boss_5 = 270,
        
        Tutorial_BranchTest_1 = 271,
        
        Avg_HelloWorld = 272,
        
        Effect_Damage_Desc = 273,
        
        Effect_Damage_Self_Desc = 274,
        
        Effect_Heal_Desc = 275,
        
        Effect_Draw_Desc = 276,
        
        Effect_Recycle_Desc = 277,
        
        Effect_Discard_Desc = 278,
        
        Effect_Neutralize_Desc = 279,
        
        Effect_Catalyze_Desc = 280,
        
        Effect_Elemental_Fire_Desc = 281,
        
        Effect_Elemental_Water_Desc = 282,
        
        Effect_Elemental_Earth_Desc = 283,
        
        Effect_Elemental_Air_Desc = 284,
        
        Effect_Buff_Burn_Enemy_Desc = 285,
        
        Effect_Buff_Burn_Self_Desc = 286,
        
        Effect_Idle_Desc = 287,
        
        Effect_Scaling_Desc = 288,
        
        Effect_LED_Water_Desc = 289,
        
        Effect_Ignite_Desc = 290,
        
        Effect_Buff_Calm_Desc = 291,
        
        Effect_Buff_Quickness_Desc = 292,
        
        Effect_Buff_Stun_Enemy_Desc = 293,
        
        Buff_Sturdy_Self_Desc = 294,
        
        Buff_Reflect_Self_Desc = 295,
        
        Buff_Reflect_Enemy_Desc = 296,
        
        Effect_Damage_Surge_Desc = 297,
        
        Effect_Damage_Self_Surge_Desc = 298,
        
        Effect_Heal_Surge_Desc = 299,
        
        Effect_Draw_Surge_Desc = 300,
        
        Effect_Damage_Madness_Desc = 301,
        
        Effect_Damage_Self_Madness_Desc = 302,
        
        Effect_Heal_Madness_Desc = 303,
        
        Effect_Draw_Madness_Desc = 304,
        
        Effect_Discard_Madness_Desc = 305,
        
        Effect_Elemental_Water_Madness_Desc = 306,
        
        Effect_Buff_Stun_Enemy_Madness_Desc = 307,
        
        Effect_Damage_Unstable_Desc = 308,
        
        Effect_Damage_Self_Unstable_Desc = 309,
        
        Effect_Heal_Unstable_Desc = 310,
        
        Effect_Draw_Unstable_Desc = 311,
        
        Effect_Damage_Cooldown_Desc = 312,
        
        Effect_Draw_Cooldown_Desc = 313,
        
        Effect_Ignite_Cooldown_Desc = 314,
        
        Effect_Calm_Cooldown_Desc = 315,
        
        Effect_Damage_Peace_Desc = 316,
        
        Effect_Draw_Peace_Desc = 317,
        
        Effect_Quickness_Peace_Desc = 318,
        
        Effect_Calm_Peace_Desc = 319,
        
        Effect_Draw_Focus_Desc = 320,
        
        Effect_Damage_Focus_Desc = 321,
        
        Buff_Sturdy_Self_Focus_Desc = 322,
        
        Buff_Reflect_Self_Focus_Desc = 323,
        
        Effect_Damage_Windborne_Desc = 324,
        
        Effect_Draw_Windborne_Desc = 325,
        
        Effect_Elemental_Air_Windborne_Desc = 326,
        
        Effect_Catalyze_Windborne_Desc = 327,
        
        Effect_Heal_Windborne_Desc = 328,
        
        Effect_Damage_Aftermath_Desc = 329,
        
        Effect_Draw_Aftermath_Desc = 330,
        
        Effect_Heal_Aftermath_Desc = 331,
        
        Tip_Enemy_HP = 332,
        
        Tip_Enemy_ATK = 333,
        
        Tip_Enemy_Reward = 334,
        
        Tip_Enemy_HP_Desc = 335,
        
        Tip_Enemy_ATK_Desc = 336,
        
        Tip_Enemy_Reward_Desc = 337,
        
        Tip_Intro_Buff = 338,
        
        Tip_Intro_Buff_Desc = 339,
        
        Tip_Intro_Properties = 340,
        
        Tip_Intro_Properties_Desc = 341,
        
        Tip_Player_HP = 342,
        
        Tip_Player_HP_Desc = 343,
        
        Tip_Player_Elemental_Water = 344,
        
        Tip_Player_Elemental_Fire = 345,
        
        Tip_Player_Elemental_Earth = 346,
        
        Tip_Player_Elemental_Air = 347,
        
        Tip_Player_Elemental_Water_Desc = 348,
        
        Tip_Player_Elemental_Fire_Desc = 349,
        
        Tip_Player_Elemental_Earth_Desc = 350,
        
        Tip_Player_Elemental_Air_Desc = 351,
        
        Tip_Player_Essence = 352,
        
        Tip_Player_Essence_Desc = 353,
        
        Tip_Player_Use = 354,
        
        Tip_Player_Use_Desc = 355,
        
        Tip_Card_Surge = 356,
        
        Tip_Card_Surge_Desc = 357,
        
        Tip_Card_Madness = 358,
        
        Tip_Card_Madness_Desc = 359,
        
        Tip_Card_Unstable = 360,
        
        Tip_Card_Unstable_Desc = 361,
        
        Tip_Card_Cooldown = 362,
        
        Tip_Card_Cooldown_Desc = 363,
        
        Tip_Card_Neutralize = 364,
        
        Tip_Card_Neutralize_Desc = 365,
        
        Tip_Card_Catalyze = 366,
        
        Tip_Card_Catalyze_Desc = 367,
        
        Tip_Card_Burn = 368,
        
        Tip_Card_Burn_Desc = 369,
        
        Tip_Card_Stun = 370,
        
        Tip_Card_Stun_Desc = 371,
        
        Tip_Card_Peace = 372,
        
        Tip_Card_Peace_Desc = 373,
        
        Tip_Card_Calm = 374,
        
        Tip_Card_Calm_Desc = 375,
        
        Tip_Card_Swift = 376,
        
        Tip_Card_Swift_Desc = 377,
        
        Tip_Card_Recycle = 378,
        
        Tip_Card_Recycle_Desc = 379,
        
        Tip_Card_Sturdy = 380,
        
        Tip_Card_Sturdy_Desc = 381,
        
        Tip_Card_Reflect = 382,
        
        Tip_Card_Reflect_Desc = 383,
        
        Tip_Card_Focus = 384,
        
        Tip_Card_Focus_Desc = 385,
        
        Tip_Card_Tailwind = 386,
        
        Tip_Card_Tailwind_Desc = 387,
        
        Tip_Card_Windborne = 388,
        
        Tip_Card_Windborne_Desc = 389,
        
        Tip_Card_Aftermath = 390,
        
        Tip_Card_Aftermath_Desc = 391,
        
        Tip_Shop_Refresh = 392,
        
        Tip_Shop_Refresh_Desc = 393,
        
        Tip_Shop_Manage = 394,
        
        Tip_Shop_Manage_Desc = 395,
        
        Tip_Shop_Buy = 396,
        
        Tip_Shop_Buy_Desc = 397,
        
        Tip_Shop_Leave = 398,
        
        Tip_Shop_Leave_Desc = 399,
        
        Tip_Shop_Delete = 400,
        
        Tip_Shop_Delete_Desc = 401,
        
        Tip_ManageCard_Delete = 402,
        
        Tip_ManageCard_Delete_Desc = 403,
        
        Tip_UI_Setting_Cancel = 404,
        
        Tip_UI_Setting_Cancel_Desc = 405,
        
        Tip_UI_Setting_QuickUse = 406,
        
        Tip_UI_Setting_QuickUse_Desc = 407,
        
        Tip_Battle_InitialDeck = 408,
        
        Tip_Battle_InitialDeck_Desc = 409,
        
        Tip_Battle_Discard = 410,
        
        Tip_Battle_Discard_Desc = 411,
        
        Tip_Battle_Draw = 412,
        
        Tip_Battle_Draw_Desc = 413,
        
        Tip_Lable_Fragile = 414,
        
        Tip_Lable_Fragile_Desc = 415,
        
        Tip_Lable_Toxic = 416,
        
        Tip_Lable_Toxic_Desc = 417,
        
        Tip_Lable_HighTemp = 418,
        
        Tip_Lable_HighTemp_Desc = 419,
        
        Tip_Lable_MagicLock = 420,
        
        Tip_Lable_MagicLock_Desc = 421,
        
        Tip_ChooseLevel_Sample = 422,
        
        Tip_ChooseLevel_Sample_Desc = 423,
        
        Tip_ChooseLevel_Boss = 424,
        
        Tip_ChooseLevel_Boss_Desc = 425,
        
        Tip_ChooseLevel_Tavern = 426,
        
        Tip_ChooseLevel_Tavern_Desc = 427,
        
        Fail_Tip_1 = 428,
        
        Fail_Tip_2 = 429,
        
        Fail_Tip_3 = 430,
        
        Fail_Tip_4 = 431,
        
        Prototype_1 = 432,
        
        Prototype_2 = 433,
        
        Prototype_3 = 434,
        
        Prototype_4 = 435,
        
        Prototype_5 = 436,
        
        Prototype_6 = 437,
        
        Prototype_7 = 438,
        
        Prototype_8 = 439,
        
        Prototype_9 = 440,
        
        Prototype_10 = 441,
        
        Prototype_11 = 442,
        
        Prototype_12 = 443,
        
        Prototype_13 = 444,
        
        Prototype_14 = 445,
        
        Prototype_15 = 446,
        
        Prototype_16 = 447,
        
        Prototype_17 = 448,
        
        Prototype_18 = 449,
        
        Prototype_19 = 450,
        
        Prototype_20 = 451,
        
        Prototype_21 = 452,
        
        Prototype_22 = 453,
    }
    
    #region 
static
    public class LocalizeIdsExtensions {
        
		public static LocalizeTable.Entry Data(this LocalizeIds id) => global::WanFramework.Data.DataSystem.Instance.Load<LocalizeTable>().Get(id);
		public static LocalizeTable.Entry DataIn(this LocalizeIds id, string tablePath) => global::WanFramework.Data.DataSystem.Instance.Load<LocalizeTable>(tablePath).Get(id);
    }
    #endregion
    
    [System.SerializableAttribute()]
    public class LocalizeTable : WanFramework.Data.DataTable<LocalizeTable.Entry> {
        
        public override string TableName {
            get {
                return "LocalizeTable";
            }
        }
        
        public override void LoadFrom(global::WanFramework.Data.DataTableRawAsset rawAsset) {
            using System.IO.MemoryStream ms = new System.IO.MemoryStream(rawAsset.GetData());
            using System.IO.BinaryReader reader = new System.IO.BinaryReader(ms);
            int entryCount = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
            Game.Data.LocalizeTable.Entry[] tmpData = new Game.Data.LocalizeTable.Entry[entryCount];
            for (int i = 0; (i < entryCount); i = (i + 1)) {
                tmpData[i] = new Game.Data.LocalizeTable.Entry();
                tmpData[i].LoadFrom(reader);
            }
            if ((ms.Length > ms.Position)) {
                throw new System.Exception("Failed to load binary table");
            }
            this.data = tmpData;
        }
        
        public Game.Data.LocalizeTable.Entry Get(Game.Data.LocalizeIds id) {
            return ((Game.Data.LocalizeTable.Entry)(this.Get(((int)(id)))));
        }
        
        [System.SerializableAttribute()]
        public class Entry : WanFramework.Data.DataEntry {
            
            [UnityEngine.SerializeField()]
            private string id;
            
            [UnityEngine.SerializeField()]
            private string langEn;
            
            [UnityEngine.SerializeField()]
            private string langCn;
            
            public string Id {
                get {
                    return this.id;
                }
            }
            
            public string LangEn {
                get {
                    return this.langEn;
                }
            }
            
            public string LangCn {
                get {
                    return this.langCn;
                }
            }
            
            public virtual void LoadFrom(System.IO.BinaryReader reader) {
                // System.String this.id
                this.id = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // System.String this.langEn
                this.langEn = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // System.String this.langCn
                this.langCn = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
            }
        }
    }
}
