//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data {
    
    
    public enum TipIds {
        
        Unknown = 0,
        
        UI_Setting_Cancel = 1,
        
        UI_Setting_QuickUse = 2,
        
        Enemy_HP = 3,
        
        Enemy_ATK = 4,
        
        Enemy_Reward = 5,
        
        Player_HP = 6,
        
        Player_Elemental_Water = 7,
        
        Player_Elemental_Fire = 8,
        
        Player_Elemental_Earth = 9,
        
        Player_Elemental_Air = 10,
        
        Player_Essence = 11,
        
        Shop_Refresh = 12,
        
        Shop_Buy = 13,
        
        Shop_Manage = 14,
        
        Shop_Leave = 15,
        
        Shop_Delete = 16,
        
        ManageCard_Delete = 17,
        
        Battle_InitialDeck = 18,
        
        Battle_Discard = 19,
        
        Battle_Draw = 20,
        
        ChooseLevel_Sample = 21,
        
        ChooseLevel_Boss = 22,
        
        ChooseLevel_Tavern = 23,
        
        Intro_Buff = 24,
        
        Intro_Properties = 25,
        
        Card_Surge = 26,
        
        Card_Madness = 27,
        
        Card_Unstable = 28,
        
        Card_Neutralize = 29,
        
        Card_Catalyze = 30,
        
        Card_Burn = 31,
        
        Card_Stun = 32,
        
        Card_Peace = 33,
        
        Card_Cooldown = 34,
        
        Card_Calm = 35,
        
        Card_Swift = 36,
        
        Card_Recycle = 37,
        
        Card_Sturdy = 38,
        
        Card_Reflect = 39,
        
        Card_Focus = 40,
        
        Card_Tailwind = 41,
        
        Card_Windborne = 42,
        
        Lable_Fragile = 43,
        
        Lable_Toxic = 44,
        
        Lable_HighTemp = 45,
        
        Lable_MagicLock = 46,
    }
    
    #region 
static
    public class TipIdsExtensions {
        
		public static TipTable.Entry Data(this TipIds id) => global::WanFramework.Data.DataSystem.Instance.Load<TipTable>().Get(id);
		public static TipTable.Entry DataIn(this TipIds id, string tablePath) => global::WanFramework.Data.DataSystem.Instance.Load<TipTable>(tablePath).Get(id);
    }
    #endregion
    
    [System.SerializableAttribute()]
    public class TipTable : WanFramework.Data.DataTable<TipTable.Entry> {
        
        public override string TableName {
            get {
                return "TipTable";
            }
        }
        
        public override void LoadFrom(global::WanFramework.Data.DataTableRawAsset rawAsset) {
            using System.IO.MemoryStream ms = new System.IO.MemoryStream(rawAsset.GetData());
            using System.IO.BinaryReader reader = new System.IO.BinaryReader(ms);
            int entryCount = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
            Game.Data.TipTable.Entry[] tmpData = new Game.Data.TipTable.Entry[entryCount];
            for (int i = 0; (i < entryCount); i = (i + 1)) {
                tmpData[i] = new Game.Data.TipTable.Entry();
                tmpData[i].LoadFrom(reader);
            }
            if ((ms.Length > ms.Position)) {
                throw new System.Exception("Failed to load binary table");
            }
            this.data = tmpData;
        }
        
        public Game.Data.TipTable.Entry Get(Game.Data.TipIds id) {
            return ((Game.Data.TipTable.Entry)(this.Get(((int)(id)))));
        }
        
        [System.SerializableAttribute()]
        public class Entry : WanFramework.Data.DataEntry {
            
            [UnityEngine.SerializeField()]
            private string id;
            
            [UnityEngine.SerializeField()]
            private Game.Data.LocalizeIds title;
            
            [UnityEngine.SerializeField()]
            private Game.Data.LocalizeIds content;
            
            [UnityEngine.SerializeField()]
            private UnityEngine.Color color;
            
            public string Id {
                get {
                    return this.id;
                }
            }
            
            public Game.Data.LocalizeIds Title {
                get {
                    return this.title;
                }
            }
            
            public Game.Data.LocalizeIds Content {
                get {
                    return this.content;
                }
            }
            
            public UnityEngine.Color Color {
                get {
                    return this.color;
                }
            }
            
            public virtual void LoadFrom(System.IO.BinaryReader reader) {
                // System.String this.id
                this.id = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // Game.Data.LocalizeIds this.title
                string enum_str_2143869990 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.title = System.Enum.Parse<Game.Data.LocalizeIds>(enum_str_2143869990);
                // Game.Data.LocalizeIds this.content
                string enum_str_1006891789 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.content = System.Enum.Parse<Game.Data.LocalizeIds>(enum_str_1006891789);
                // UnityEngine.Color this.color
                this.color = WanFramework.Data.DataTableBinarySerializer.DeserializeUnityColor(reader);
            }
        }
    }
}
