//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data {
    
    
    public enum TutorialIds {
        
        Tutorial_Begin = 0,
        
        Tutorial_Setup_Character = 1,
        
        Tutorial_Setup_Resource = 2,
        
        Tutorial_Setup_Health = 3,
        
        Tutorial_Setup_Enemy = 4,
        
        Tutorial_Setup_EnemyHealth = 5,
        
        Tutorial_Setup_EnemyAttack = 6,
        
        Tutorial_Setup_EnemyReward = 7,
        
        Tutorial_Setup_DisableDrag = 8,
        
        Tutorial_Setup_DisableDraw = 9,
        
        Tutorial_Setup_EnableSelect = 10,
        
        Test = 11,
        
        Tutorial_Setup_InitialCards_1 = 12,
        
        Tutorial_Setup_InitialCards_2 = 13,
        
        Tutorial_Setup_InitialCards_3 = 14,
        
        Tutorial_1 = 15,
        
        Tutorial_2 = 16,
        
        Tutorial_3 = 17,
        
        Tutorial_4 = 18,
        
        Tutorial_5 = 19,
        
        Tutorial_6 = 20,
        
        Tutorial_7 = 21,
        
        Tutorial_8 = 22,
        
        Tutorial_9 = 23,
        
        Tutorial_10 = 24,
        
        Tutorial_11 = 25,
        
        Tutorial_11_CardDesc_1 = 26,
        
        Tutorial_11_CardDesc_2 = 27,
        
        Tutorial_11_CardDesc_3 = 28,
        
        Tutorial_12 = 29,
        
        Tutorial_12_Sacrifice = 30,
        
        Tutorial_12_Elements = 31,
        
        Tutorial_12_Wait = 32,
        
        Tutorial_12_AddHP = 33,
        
        Tutorial_12_AddATK = 34,
        
        Tutorial_12_AddReward = 35,
        
        Tutorial_12_Wait_2 = 36,
        
        Tutorial_13 = 37,
        
        Tutorial_14 = 38,
        
        Tutorial_15_CardDetail_1 = 39,
        
        Tutorial_15_CardDetail_2 = 40,
        
        Tutorial_15 = 41,
        
        Tutorial_15_Addition = 42,
        
        Tutorial_15_Attack_Message = 43,
        
        Tutorial_15_Attack = 44,
        
        Tutorial_15_Attack_2 = 45,
        
        Tutorial_15_Wait = 46,
        
        Tutorial_16 = 47,
        
        Tutorial_17 = 48,
        
        Tutorial_20 = 49,
        
        Tutorial_21 = 50,
        
        Tutorial_21_PlayUseCard = 51,
        
        Tutorial_21_Wait = 52,
        
        Tutorial_21_Effects = 53,
        
        Tutorial_21_Attack_1 = 54,
        
        Tutorial_21_Attack_2 = 55,
        
        Tutorial_21_Attack_3 = 56,
        
        Tutorial_21_Attack_4 = 57,
        
        Tutorial_21_Attack_5 = 58,
        
        Tutorial_21_Attack_6 = 59,
        
        Tutorial_21_Attack_7 = 60,
        
        Tutorial_21_Wait2 = 61,
        
        Tutorial_22 = 62,
        
        Tutorial_21_EnemyAttack = 63,
        
        Tutorial_21_EnemyAttack_2 = 64,
        
        Tutorial_21_Wait3 = 65,
        
        Tutorial_23_Start = 66,
        
        Tutorial_23_1 = 67,
        
        Tutorial_23_2 = 68,
        
        Tutorial_23_Draw = 69,
        
        Tutorial_23_Wait_1 = 70,
        
        Tutorial_23_Draw_3 = 71,
        
        Tutorial_23_Draw_4 = 72,
        
        Tutorial_23_Draw_2 = 73,
        
        Tutorial_23_Attack = 74,
        
        Tutorial_23_Attack_2 = 75,
        
        Tutorial_23_Wait_2 = 76,
        
        Tutorial_27 = 77,
        
        Tutorial_18 = 78,
        
        Tutorial_19 = 79,
        
        Tutorial_24 = 80,
        
        Tutorial_25 = 81,
        
        Tutorial_26 = 82,
        
        Tutorial_End = 83,
        
        Tutorial_12_Branch = 84,
        
        Tutorial_Branch1_Beg = 85,
        
        Tutorial_Branch1_Msg = 86,
        
        Tutorial_Branch1_End = 87,
        
        Tutorial_Branch2_Beg = 88,
        
        Tutorial_Branch2_Msg = 89,
        
        Tutorial_Branch2_PlaySacrificeCard = 90,
        
        Tutorial_Branch2_InitialCards_5 = 91,
        
        Tutorial_Branch2_End = 92,
        
        BranchTest1_Beg = 93,
        
        BranchTest1_End = 94,
        
        BranchTest2_Beg = 95,
        
        BranchTest2_End = 96,
        
        Tutorial_Setup_BranchTest_1 = 97,
        
        Tutorial_Setup_BranchTest_2 = 98,
        
        BranchTest_1 = 99,
        
        BranchTest_1_Root = 100,
        
        Tutorial_MainMenu_Begin = 101,
        
        Tutorial_MainMenu_HelloWorld = 102,
        
        Tutorial_MainMenu_End = 103,
        
        Tutorial_EnterCharaSelection_Begin = 104,
        
        Tutorial_EnterCharaSelection = 105,
        
        Tutorial_EnterCharaSelection_2 = 106,
        
        Tutorial_EnterCharaSelection_3 = 107,
        
        Tutorial_EnterCharaSelection_End = 108,
        
        Tutorial_EnterMap_Begin = 109,
        
        Tutorial_EnterMap = 110,
        
        Tutorial_EnterMap_2 = 111,
        
        Tutorial_EnterMap_3 = 112,
        
        Tutorial_EnterMap_4 = 113,
        
        Tutorial_EnterMap_5 = 114,
        
        Tutorial_EnterMap_6 = 115,
        
        Tutorial_EnterMap_7 = 116,
        
        Tutorial_EnterMap_8 = 117,
        
        Tutorial_EnterMap_End = 118,
        
        Tutorial_HealthBelow25_Begin = 119,
        
        Tutorial_HealthBelow25 = 120,
        
        Tutorial_HealthBelow25_End = 121,
        
        Tutorial_Reward_Begin = 122,
        
        Tutorial_Reward_1 = 123,
        
        Tutorial_Reward_2 = 124,
        
        Tutorial_Reward_3 = 125,
        
        Tutorial_Reward_4 = 126,
        
        Tutorial_Reward_5 = 127,
        
        Tutorial_Reward_6 = 128,
        
        Tutorial_Reward_End = 129,
        
        Tutorial_Shop_Begin = 130,
        
        Tutorial_Shop_1 = 131,
        
        Tutorial_Shop_2 = 132,
        
        Tutorial_Shop_3 = 133,
        
        Tutorial_Shop_4 = 134,
        
        Tutorial_Shop_5 = 135,
        
        Tutorial_Shop_6 = 136,
        
        Tutorial_Shop_End = 137,
        
        Tutorial_ShopUpdate_Begin = 138,
        
        Tutorial_ShopUpdate_1 = 139,
        
        Tutorial_ShopUpdate_2 = 140,
        
        Tutorial_ShopUpdate_3 = 141,
        
        Tutorial_ShopUpdate_4 = 142,
        
        Tutorial_ShopUpdate_5 = 143,
        
        Tutorial_ShopUpdate_6 = 144,
        
        Tutorial_ShopUpdate_7 = 145,
        
        Tutorial_ShopUpdate_8 = 146,
        
        Tutorial_ShopUpdate_9 = 147,
        
        Tutorial_ShopUpdate_10 = 148,
        
        Tutorial_ShopUpdate_11 = 149,
        
        Tutorial_ShopUpdate_12 = 150,
        
        Tutorial_ShopUpdate_13 = 151,
        
        Tutorial_ShopUpdate_End = 152,
        
        Tutorial_Boss_Begin = 153,
        
        Tutorial_Boss_1 = 154,
        
        Tutorial_Boss_2 = 155,
        
        Tutorial_Boss_3 = 156,
        
        Tutorial_Boss_4 = 157,
        
        Tutorial_Boss_5 = 158,
        
        Tutorial_Boss_End = 159,
    }
    
    #region 
static
    public class TutorialIdsExtensions {
        
		public static TutorialTable.Entry Data(this TutorialIds id) => global::WanFramework.Data.DataSystem.Instance.Load<TutorialTable>().Get(id);
		public static TutorialTable.Entry DataIn(this TutorialIds id, string tablePath) => global::WanFramework.Data.DataSystem.Instance.Load<TutorialTable>(tablePath).Get(id);
    }
    #endregion
    
    [System.SerializableAttribute()]
    public class TutorialTable : WanFramework.Data.DataTable<TutorialTable.Entry> {
        
        public override string TableName {
            get {
                return "TutorialTable";
            }
        }
        
        public override void LoadFrom(global::WanFramework.Data.DataTableRawAsset rawAsset) {
            using System.IO.MemoryStream ms = new System.IO.MemoryStream(rawAsset.GetData());
            using System.IO.BinaryReader reader = new System.IO.BinaryReader(ms);
            int entryCount = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
            Game.Data.TutorialTable.Entry[] tmpData = new Game.Data.TutorialTable.Entry[entryCount];
            for (int i = 0; (i < entryCount); i = (i + 1)) {
                tmpData[i] = new Game.Data.TutorialTable.Entry();
                tmpData[i].LoadFrom(reader);
            }
            if ((ms.Length > ms.Position)) {
                throw new System.Exception("Failed to load binary table");
            }
            this.data = tmpData;
        }
        
        public Game.Data.TutorialTable.Entry Get(Game.Data.TutorialIds id) {
            return ((Game.Data.TutorialTable.Entry)(this.Get(((int)(id)))));
        }
        
        [System.SerializableAttribute()]
        public class Entry : WanFramework.Data.DataEntry {
            
            [UnityEngine.SerializeField()]
            private string id;
            
            [UnityEngine.SerializeField()]
            private Game.Data.LocalizeIds message;
            
            [UnityEngine.SerializeField()]
            private int messageSlot;
            
            [UnityEngine.SerializeField()]
            private string vfxPrefab;
            
            [UnityEngine.SerializeField()]
            private Game.Data.TutorialCondition condition;
            
            [UnityEngine.SerializeField()]
            private string[] conditionArgs;
            
            [UnityEngine.SerializeField()]
            private float actionDelay;
            
            [UnityEngine.SerializeField()]
            private Game.Data.TutorialAction action;
            
            [UnityEngine.SerializeField()]
            private string[] actionArgs;
            
            [UnityEngine.SerializeField()]
            private bool isEnd;
            
            public string Id {
                get {
                    return this.id;
                }
            }
            
            public Game.Data.LocalizeIds Message {
                get {
                    return this.message;
                }
            }
            
            public int MessageSlot {
                get {
                    return this.messageSlot;
                }
            }
            
            public string VfxPrefab {
                get {
                    return this.vfxPrefab;
                }
            }
            
            public Game.Data.TutorialCondition Condition {
                get {
                    return this.condition;
                }
            }
            
            public string[] ConditionArgs {
                get {
                    return this.conditionArgs;
                }
            }
            
            public float ActionDelay {
                get {
                    return this.actionDelay;
                }
            }
            
            public Game.Data.TutorialAction Action {
                get {
                    return this.action;
                }
            }
            
            public string[] ActionArgs {
                get {
                    return this.actionArgs;
                }
            }
            
            public bool IsEnd {
                get {
                    return this.isEnd;
                }
            }
            
            public virtual void LoadFrom(System.IO.BinaryReader reader) {
                // System.String this.id
                this.id = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // Game.Data.LocalizeIds this.message
                string enum_str_1684368187 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.message = System.Enum.Parse<Game.Data.LocalizeIds>(enum_str_1684368187);
                // System.Int32 this.messageSlot
                this.messageSlot = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                // System.String this.vfxPrefab
                this.vfxPrefab = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                // Game.Data.TutorialCondition this.condition
                string enum_str_787549961 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.condition = System.Enum.Parse<Game.Data.TutorialCondition>(enum_str_787549961);
                // System.String[] this.conditionArgs
                int array_size_1867599692 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.conditionArgs = new string[array_size_1867599692];
                for (int array_size_1867599692_i = 0; (array_size_1867599692_i < array_size_1867599692); array_size_1867599692_i = (array_size_1867599692_i + 1)) {
                    // System.String this.conditionArgs[array_size_1867599692_i]
                    this.conditionArgs[array_size_1867599692_i] = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                }
                // System.Single this.actionDelay
                this.actionDelay = WanFramework.Data.DataTableBinarySerializer.DeserializeSingle(reader);
                // Game.Data.TutorialAction this.action
                string enum_str_771234150 = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                this.action = System.Enum.Parse<Game.Data.TutorialAction>(enum_str_771234150);
                // System.String[] this.actionArgs
                int array_size_1737057891 = WanFramework.Data.DataTableBinarySerializer.DeserializeInt32(reader);
                this.actionArgs = new string[array_size_1737057891];
                for (int array_size_1737057891_i = 0; (array_size_1737057891_i < array_size_1737057891); array_size_1737057891_i = (array_size_1737057891_i + 1)) {
                    // System.String this.actionArgs[array_size_1737057891_i]
                    this.actionArgs[array_size_1737057891_i] = WanFramework.Data.DataTableBinarySerializer.DeserializeString(reader);
                }
                // System.Boolean this.isEnd
                this.isEnd = WanFramework.Data.DataTableBinarySerializer.DeserializeBool(reader);
            }
        }
    }
}
